apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    home.apps.service: dns
  name: dns
  namespace: home-apps
spec:
  type: NodePort
  selector:
    home.apps.service: dns # home.apps.service=dnsのpod
  ports:
    - name: dns
      port: 53
      targetPort: 53
      nodePort: 53
      protocol: UDP
