apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    home.apps.service: ntp
  name: ntp
  namespace: home-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      home.apps.service: ntp
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        home.apps.service: ntp
    spec:
      hostname: ntp
      restartPolicy: Always
      containers:
        - image: localhost:30080/ntp
          name: ntp
          ports:
            - containerPort: 123
              protocol: UDP
            - containerPort: 323
              protocol: UDP
          securityContext:
            privileged: true
          resources: {}
          volumeMounts:
            - name: ntp-conf
              mountPath: /etc/chrony
      volumes:
        - name: ntp-conf
          configMap:
            name: ntp-conf # マウントしたいConfigMapの名前
            items: # ファイルとして作成するConfigMapのキーの配列, 記載した特定のものだけをconfigmapから持ってくる
              - key: chrony.conf
                path: chrony.conf
                mode: 0644

status: {}
